{-# LANGUAGE TemplateHaskell #-}
module Examples.KnownItems where

import MSBuildGen.DSL.Items

items [ "CustomBuild"
      , "CustomBuildStep"
      , "ClCompile"
      , "Lib"
      , "ImpLib"
      , "Link"
      , "Midl"
      , "ResourceCompile"
      , "Manifest"
      , "ManifestResourceCompile"
      , "XdcMake"
      , "BscMake"
      , "XSD"
      , "Xsd"
      , "ProjectReference"
      , "Reference"
      , "COMReference"
      , "PreBuildEvent"
      , "PreLinkEvent"
      , "PostBuildEvent"
      , "BuildLog"
      , "ManagedTargetPath"
      ]

string "Message"
path "TrackerLogDirectory"
bool "MinimalRebuildFromTracking"
path "OutputFile"
bool "SuppressStartupBanner"
customList "AcceptableNonZeroExitCodes_Metadata" "AcceptableNonZeroExitCodes"
path "TypeLibraryName"
string "TargetEnvironment"
string "WarningLevel"
string "DefaultCharType"
bool "IgnoreStandardIncludePath"
bool "WarnAsError"
bool "GenerateTypeLibrary"
bool "ErrorCheckAllocations"
bool "ErrorCheckBounds"
bool "ErrorCheckEnumRange"
bool "ErrorCheckRefPointers"
bool "ErrorCheckStubData"
string "StructMemberAlignment"
path "HeaderFileName"
path "ResourceOutputFileName"
string "Culture"
bool "VerboseOutput"
bool "GenerateCatalogFiles"
bool "UpdateFileHashes"
path "OutputManifestFile"
bool "UseUnicodeResponseFiles"
bool "ValidateIntelliSense"
bool "PreserveSBR"
string "Namespace"
string "GenerateFromSchema"
bool "LinkLibraryDependencies"
bool "UseLibraryDependencyInputs"
bool "ReferenceOutputAssembly"
bool "Private"
bool "CopyLocalSatelliteAssemblies"
customString "Language_Metadata" "Language"
customPath "Path_Metadata" "Path"
string "PrecompiledHeader"
string "Command"
bool "ExcludedFromBuild"
bool "GenerateXMLDocumentationFiles"
